-- disable for MacOS
-- vim.g.clipboard = {
--    name = 'xclip-xfce4-clipman',
--    copy = {
--       ['+'] = 'xclip -selection clipboard',
--       ['*'] = 'xclip -selection clipboard',
--   },
--  paste = {
--   ['+'] = 'xclip -selection clipboard -o',
--  ['*'] = 'xclip -selection clipboard -o',
--  },
--  cache_enabled = false,
-- }
